### ISSUE TITLE
Merging classifications & checking statistical Values fall outside boundaries

### ISSUE THREAD

**Issue by hugo-e-pigott** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#105]
Merging the classifications with new function the outputs are great! I've checked and the missing values for BEC are correct and we need to add to our classifications. Just two issues:
- It is saying that all SITC classifications 0-9 are missing from classifications table. I am assuming the function is not reading in the classification table properly but could be wrong, I went through the function but couldn't make out the issue. Could you please check?
- Previously when ran the old code for merging principle commodities which uses HS.Code there were lots of missing classifications. However now there is no output, again not sure why. Would it be possible to check this again?

Last thing is checking if values fall outside the boundaries, the issue is
<img width="350" alt="Screenshot 2021-10-27 at 16 18 16" src="https://user-images.githubusercontent.com/65749107/139005428-a9de2f8b-3435-4cd2-a7fa-bcee71e111c4.png">

Would it be possible too check this too?

**Comment by JosephCrispell** [comment]
> The SITC_1 is showing all classifications missing

The latest version of `master` branch should have this issue fixed, try a `git pull` and run the code again. It was caused by a formatting issue. This has also fixed:

> I just wanted to add looking at the processed data file today the classification descriptions for SITC have not been added, all column values are "NA"

**Comment by JosephCrispell** [comment]
> HS.Code shows no missing but in previous function there were quite a few

For the original code gave this warning: 
```
Warning message:
In checkMergingColumnsForClassificationTables(tradeStatsCommoditiesMergedWithClassifications,  :
  12 codes in the "HS.Code_2" column of the HS descriptions classification table are not in the "HS.Code_2" column of the trades statistics table.
```
Giving:
```
> missingValuesHSCode_2
$NotPresentInClassificationTable
character(0)

$NotPresentInTradesData
 [1] "13" "26" "43" "47" "50" "53" "55" "75" "77" "80" "81" "93"
```

And the new method gives:
|                 file                             |                 link_column    |                 codes_in_trades_not_in_classification    |                 codes_in_classification_not_in_trades    |                 n_codes_in_trades_not_in_classification    |                 n_codes_in_classification_not_in_trades              |
|--------------------------------------------------|--------------------------------|----------------------------------------------------------|----------------------------------------------------------|------------------------------------------------------------|----------------------------------------------------------------------|
| OPN_FINAL_ASY_HSCodeClassifications_31-01-20.csv | HS.Code_2                      |                                                          | 13;26;43;47;50;53;55;75;77;80;81;93                      | 0                                                          | 12                                                                   |

On checking the remaining merges, an inconsistency on the principle commodities is caused by an error in the previous version of the code: 
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/0dbaa4f37cda70fe52ccf3f0dbf6223c9e850d17/R/MonthlyReportAndTables/1_processLatestMonthsTradeStats.R#L193-L198
Where the `HS.Code` of the `principleCommodityClassification` is not getting updated - leading to many HS codes not being found in classification table.

Other discrepancies in the numbers are caused by the `checkMergingColumnsForClassificationTables()` function counting all values instead of unique values.

Let me know if the above makes sense and if the latest version of the code is working ok for you.

**Comment by JosephCrispell** [comment]
The `missingClassificiationCodeInfo` looks like this from my side:
|             file                                                   |                 link_column    |                 codes_in_trades_not_in_classification    |                 codes_in_classification_not_in_trades    |                 n_codes_in_trades_not_in_classification    |                 n_codes_in_classification_not_in_trades              |
|--------------------------------------------------------------------|--------------------------------|----------------------------------------------------------|----------------------------------------------------------|------------------------------------------------------------|----------------------------------------------------------------------|
| OPN_FINAL_ASY_ModeOfTransportClassifications_31-01-20.csv          | Office                         |                                                          |                                                          | 0                                                          | 0                                                                    |
| OPN_FINAL_ASY_HSCodeClassifications_31-01-20.csv                   | HS.Code_2                      |                                                          | ...                                                      | 0                                                          | 12                                                                   |
| OPN_FINAL_ASY_SITCCodeClassifications_31-01-20.csv                 | SITC_1                         |                                                          |                                                          | 0                                                          | 0                                                                    |
| OPN_FINAL_ASY_CountryDescriptionImportClassifications_31-01-20.csv | CO                             |                                                          | ...                                                      | 0                                                          | 185                                                                  |
| OPN_FINAL_ASY_CountryDescriptionExportClassifications_31-01-20.csv | CE.CD                          |                                                          | ...                                                      | 0                                                          | 193                                                                  |
| OPN_FINAL_ASY_PrincipleCommoditiesClassifications_31-01-20.csv     | HS.Code                        |                                                          | ...                                                      | 0                                                          | 3627                                                                 |
| OPN_FINAL_ASY_BECClassifications_31-01-20.csv                      | HS.Code_6                      | ...                                                      | ...                                                      | 9                                                          | 3554                                                                 |
