### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by hugo-e-pigott** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#114]
Realised that there were issues with the initial analysis when merging, so have had to rerun everything. Attached are raw and processed data-sets now working with.

[VNSO_RAP_Trade_DataSets.zip](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/files/7743084/VNSO_RAP_Trade_DataSets.zip)

With the datasets used the processed ones, as have recoded some of information for outputs- such as SRAP METAL from SRAP METAL, SCRAP METALS etc.

Will go through issues in todays session. 

issues:
- Non-numeric argument for Trade Agreement 

<img width="902" alt="Screenshot 2021-12-20 at 18 45 06" src="https://user-images.githubusercontent.com/65749107/146730942-646da78b-3a0d-4711-bf61-ec4f2ffa187e.png">

- Imports of dietary risk factors merging

<img width="903" alt="Screenshot 2021-12-20 at 18 50 56" src="https://user-images.githubusercontent.com/65749107/146731533-0d190c0e-46f0-44d3-b368-0142600b4953.png">

- imports that can be substituted 

<img width="900" alt="Screenshot 2021-12-20 at 18 45 45" src="https://user-images.githubusercontent.com/65749107/146731049-66467c91-efbf-4b87-8876-123e3b21cee6.png">

Also if possible can you build a report and send to me so know what we I need to aim at for the others.

Cheers Joe and merry Christmas and Happy New Year!

**Comment by JosephCrispell** [comment]
> Non-numeric argument for Trade Agreement 

Fixed this - these were  columns with no values and the `adorn_totals()` function was introducing a "-" by default that caused some issues. Resolved here:
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/77f58b048ac641f999017a2a17a12adf066a90af/R/MonthlyReportAndTables/3_buildMonthlyReport.Rmd#L750-L755

**Comment by JosephCrispell** [comment]
> Imports of dietary risk factors merging

The increase in observations is caused by duplicate `HS.Code`s in the `productsRelatedHealth` data.frame, here are the counts for `HS.Code`s with multiple values:

| 16010000 | 16021000 | 16022000 | 16023100 | 16023200 | 16024100 | 16024900 | 16025090 | 16029020 | 16029030 | 16029090 | 18062000 | 18069000 | 19041000 | 19049000 | 20091200 | 20098900 | 22019000 | 22021000 | 22029900 |
| ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- |
|       2    |    2  |      2    |    2    |    2    |    2   |     2    |    2   |     2    |    2    |    2    |    2    |    2    |    3  | 3    |    2    |    2    |    2     |   2      |  3 |

**Comment by JosephCrispell** [comment]
> imports that can be substituted

Similar to above the `HS.Code` `04072900` is repeated in the `importsSubstitutionChickenFish` data.frame, resulting in an increase in the number of observations.

**Comment by JosephCrispell** [comment]
> Plot resolution and X axis tick labels

I found out [here](https://github.com/tidyverse/ggplot2/issues/3094) that this wobbly text is caused by low resolution. After some playing around I found you can use the `dpi` cell parameter to change figure resolution - so I added `dpi = 600` here and it seems to have worked:
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/46e3310bd869d2f67cd2ec909b8a90f84e656db0/R/MonthlyReportAndTables/3_buildMonthlyReport.Rmd#L10-L12

**Comment by JosephCrispell** [comment]
Finally, been playing around with the formatting:
- Moving `######### Page break` around to where page breaks make sense
- Using `&nbsp;  ` to add new lines - often you'll need a few of these to add a vertical space
