### ISSUE TITLE
Getting Script 1(processing) and 2(tables) functioning 

### ISSUE THREAD

**Issue by hugo-e-pigott** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#93]
Script 1

- [x] Converting SITC to character challenge with Padding. Currently 25 warnings- one being SITC Code 23 in csv, in xlsx it is 023.0, and there are a few others.

- [x] Check for missing values, need to create data frame for all missing values to investigate further. Have to create column of unique identifiers so can go back to raw data and make changes. 

- [x] Extracting SITC, again create data frame for all Null etc vales. Similar to above use unique identifiers to investigate further and go back and adapt the raw data.

- [x] For Merging HS 2 Codes I tried to adapt function but didn't work. Ended up writing line of code to pad zeros. How would you adapt function to do this?

- [x] The function, infoAboutMissingObservations() how exactly does this work?

- [ ] The check for historical data is giving an error: "Error in rep(0, length-char (hs(code)): invalid times argument". Could be leading zeros again?

Script 2

- [ ] When extracting data from R to csv get error, "could not find function writeData().

**Comment by JosephCrispell** [comment]
*Converting SITC to character challenge with Padding. Currently 25 warnings- one being SITC Code 23 in csv, in xlsx it is 023.0, and there are a few others.*

I get the following five warnings, running on my side:

    Warning messages:
     1: In FUN(X[[i]], ...) :
       Format of current SITC code (8431.2) isn't in the expected form: 000.00. Code will remain unchanged.
    2: In FUN(X[[i]], ...) :
      Format of current SITC code (0401.2) isn't in the expected form: 000.00. Code will remain unchanged.
    3: In FUN(X[[i]], ...) :
      Format of current SITC code (0401.2) isn't in the expected form: 000.00. Code will remain unchanged.
    4: In FUN(X[[i]], ...) :
      Format of current SITC code (8431.2) isn't in the expected form: 000.00. Code will remain unchanged.
    5: In FUN(X[[i]], ...) :
      Format of current SITC code (8431.2) isn't in the expected form: 000.00. Code will remain unchanged.

I've updated `padWithZeros()` function to work for values like 23, so hopefully that reduces the number of errors you are seeing.

**Comment by JosephCrispell** [comment]
*For Merging HS 2 Codes I tried to adapt function but didn't work. Ended up writing line of code to pad zeros. How would you adapt function to do this?*

I've added an `nDigits` parameter to the `padWithZeros` function so that you can pad HS codes to any number of digits. With the updated function you can replace `str_pad(hsDescription$HS.Code_2, 2, pad = "0")` with `sapply(hsDescription$HS.Code_2, FUN=padWithZeros, "HS", 2)`.

I must admit I think I think I prefer the code you used but either will work fine 😊

**Comment by JosephCrispell** [comment]
*The function, infoAboutMissingObservations() how exactly does this work?*

The `searchForMissingObservations()` function is checking for missing values in a column brought in from one of the merges - a way of identifying where codes in the trade statistics data are missing in the classification tables. 

I think this function is over complicated so I've added some simpler code that checks whether codes are missing alongside each merge:
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/60a8f118a8bb10a6148623842135a62064356ab0/R/MonthlyReportAndTables/1_processLatestMonthsTradeStats.R#L125-L128

The code above checks to see if there are any values in the `Office` column of the trade statistics data that aren't present in the Mode of Transport classification table. This code is hopefully simpler and can be easily adapted for each merge.

For example, the code below checks if there are any values in the `SITC_2` column that are missing in the SITC classifications table:
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/60a8f118a8bb10a6148623842135a62064356ab0/R/MonthlyReportAndTables/1_processLatestMonthsTradeStats.R#L138-L141

I've adapted the above code for each merge and a warning will be printed whenever codes in the trades statistics aren't found in the classifications table.

**Comment by JosephCrispell** [comment]
*Extracting SITC, again create data frame for all Null etc vales. Similar to above use unique identifiers to investigate further and go back and adapt the raw data.*

There are a couple of NA values in the SITC column causing the Null value warning messages. I've added some code to view the rows with NA values: 
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/5b9c62b8637aa09ea706e6ae4bb0813144fef5f5/R/MonthlyReportAndTables/1_processLatestMonthsTradeStats.R#L202-L207

The above code is quite simplistic and a more targeted and informative piece of code could be written.

**Comment by JosephCrispell** [comment]
*The check for historical data is giving an error: "Error in rep(0, length-char (hs(code)): invalid times argument". Could be leading zeros again?*

I'm not seeing this error - could you give a few more details? I've updated the `checkCommodityValues()` function to use the `padWithZeros()` function, which has an NA check so that may remove the error

**Comment by JosephCrispell** [comment]
Script 2:
*When extracting data from R to csv get error, "could not find function writeData().*

Can you provide a few more details on this erro message - what line of `2_insertLatestMonthsDataIntoFormattedTables.R` are you running. I am getting the following error at line 19:

    Error in openxlsx::loadWorkbook(finalWorkbookFileName) : 
       File does not exist.

Because I don't have the `SEC_FINAL_MAN_FinalTradeStatisticsTables_30-12-19_WORKING.xlsx` file, I only have the folloiwing files in my outputs folder:
    SEC_FINAL_MAN_FinalTradeStatisticsTables_30-11-19_ORIGINAL.xlsx
    SEC_FINAL_MAN_FinalTradeStatisticsTables_30-11-19_WORKING.xlsx
    SEC_FINAL_MAN_FinalTradeStatisticsTables_31-01-20_ORIGINAL.xlsx

**Comment by JosephCrispell** [comment]
Hi @hugo-e-pigott,

I've looked into each of the issues you highlighted and added some comments above - let me know if they make sense.

Thanks,

Joe

**Comment by hugo-e-pigott** [comment]
Hi Joe 

Thank you for the comments and adaptations to the code!


Processing Script (1)

- Only issue now when converting SITC is with code "8431.2", checked in xlsx- same. The corresponding HS Code is 84312000, so think error from Customs, will follow up.

- Exploring the extent of missing data, not able to view the Dataframe, not sure why

- Merging with SITC, able to view the discrepancy but need data.frame to include unique number to investigate further in raw dataset

- Merging Principle Commodities, says 378 codes not in classifications. Not sure how this is possible as previously only a few observations dropped after merge. Again need data.frame with unique numbers so can investigate further in raw data. Also is it possible to highlight what the unique principle commodities that are missing, as have a number of duplications?

- Merging BEC, similar issues to Principle Commodities, again greater difference now that previous function infoMissingObservations() I think nearly 700. We can however leave this as we still need to sort of the classifications 

- Checked number of NA values, got error "could not find function nrows"

- Checked code CommoditiesWithExpectations, got error "names do not match previous names"

Tables Script (2) 

- Trying to change outputs file from xlsx to csv with multiple sheets not able to do this. Something either doing wrong or misunderstood?

- Got two errors below when running code trying to extract data frame into excel. 
<img width="773" alt="Screenshot 2021-05-12 at 14 27 36" src="https://user-images.githubusercontent.com/65749107/117919741-43fb9100-b339-11eb-8274-ebf7a2578edc.png">
<img width="709" alt="Screenshot 2021-05-12 at 14 27 21" src="https://user-images.githubusercontent.com/65749107/117919748-4827ae80-b339-11eb-8ed0-d26b5662b85c.png">

**Comment by JosephCrispell** [comment]
> * Only issue now when converting SITC is with code "8431.2", checked in xlsx- same. The corresponding HS Code is 84312000, so think error from Customs, will follow up.

Yes, I'm getting the same warning on my side and it'll be useful to flag with Customs. I also get a warning for `0401.2` - is something that should be flagged or should we update the `padWithZeros()` function to allow it?

> * Exploring the extent of missing data, not able to view the Dataframe, not sure why

There were a couple of missing brackets that I've now updated and you should be able to view the data.frame now.

> * Merging with SITC, able to view the discrepancy but need data.frame to include unique number to investigate further in raw dataset

I've updated the warning message so it doesn't just select the column of interest but retains all columns. Now in the subset you are viewing the `RawDataRowID` column should give the row in the raw data file.

> * Merging Principle Commodities, says 378 codes not in classifications. Not sure how this is possible as previously only a few observations dropped after merge. Again need data.frame with unique numbers so can investigate further in raw data. Also is it possible to highlight what the unique principle commodities that are missing, as have a number of duplications?

This warning is saying which HS codes in the raw data **aren't** in the principle commodities table - so in that case it isn't surprising that `378` codes are missing as there probably aren't principle commodities. It does mean that it is probably worth add a check for any codes in the classification table that aren't in the raw data - I have added this function:
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/fbdd54003b0c312c9c51325d901101d1439548a8/R/functions.R#L10-L30
That checks whether values are missing in the column used to merge in both the trade statistics data and the classification table, which gives a wee bit more information to work with.

> * Merging BEC, similar issues to Principle Commodities, again greater difference now that previous function infoMissingObservations() I think nearly 700. We can however leave this as we still need to sort of the classifications

As above - I think we need to look into these further and I've added a simpler function that will hopefully help pinpoint which values are missing in the trades data or the classification table.

> * Checked number of NA values, got error "could not find function nrows"

Got the same - fixed it now - should have been `nrow()` function.

> * Checked code CommoditiesWithExpectations, got error "names do not match previous names"

I'm not getting this error - could you provide a wee bit more information? I've added the `RawDataRowID` as a column of interest so that we can check back in the raw data if needed.

**Comment by JosephCrispell** [comment]
I've started testing the `R/MonthlyReportAndTables/3_buildMonthlyReport.Rmd` the script but I think I am missing a few of the required input files.
